# Generated by ./configure
#
# Absolute paths to the tree-sitter installation folders.
# This file is meant to be sourced in shell scripts as follows:
#
#   source ./tree-sitter-config.sh
#
# or equivalently:
#
#   . ./tree-sitter-config.sh
#
TREESITTER_BINDIR="/home/cmr/semgrep_repos/new/ocaml-tree-sitter-semgrep/tree-sitter/bin"
TREESITTER_INCDIR="/home/cmr/semgrep_repos/new/ocaml-tree-sitter-semgrep/tree-sitter/include"
TREESITTER_LIBDIR="/home/cmr/semgrep_repos/new/ocaml-tree-sitter-semgrep/tree-sitter/lib"
PATH=$TREESITTER_BINDIR:$PATH
export TREESITTER_BINDIR
export TREESITTER_INCDIR
export TREESITTER_LIBDIR
export PATH
